class ViewHomeController {
  constructor($state) {
    'ngInject'

    this.welcomeMessage = 'Welcome message generated by AngularJS'
  }
}

export const ViewHome = {
  controller: ViewHomeController,
  templateUrl: 'components/home/partials/view-home.html'
}
