class ViewHomeController {
  constructor($state) {
    'ngInject'

    this.welcomeMessage = 'Welcome message generated by AngularJS'
  }
  uiCanExit() {
    console.log('ViewHomeController::uiCanExit')
  }
  uiOnParamsUpdated(newValues, $transition) {
    console.log('ViewHomeController::uiCanExit', newValues, $transition)
  }
  $onInit() {
    console.log('ViewHomeController::$onInit')
  }
}

export const ViewHome = {
  controller: ViewHomeController,
  templateUrl: 'components/home/partials/view-home.html'
}
