'use strict';

/* https://github.com/angular/protractor/blob/master/docs/toc.md */

function assertTextValueByCSS(selector, regexp) {
  expect(element.all(by.css(selector)).first().getText()).toMatch(regexp);
}

describe('my app', function() {

  browser.get('index.html');

  it('base path should be index.html', function() {
    expect(browser.getLocationAbsUrl()).toMatch('');
  });

  describe('home', function() {

    beforeEach(function() {
      browser.get('index.html');
    });

    it('should render home view', function() {
      assertTextValueByCSS('main h1', /AngularJS Devstack/);
      assertTextValueByCSS('main p', /Welcome message generated by AngularJS/);
    });

  });

});
